<?php

/**
 * Implements hook_preprocess_html().
 *
 */
function sweetscented_preprocess_html(&$variables){
  $variables['attributes']['route-name'] = \Drupal::routeMatch()->getRouteName();
}

/**
 * Implements hook_preprocess_page().
 *
 */
 function sweetscented_preprocess_page(&$variables){
//     $route_name = \Drupal::routeMatch()->getRouteName();
//     print_r($route_name);
//     die();
 }
